### ISSUE TITLE
Blinds are not going fully up/down

### ISSUE THREAD

**Issue by mschaeuble** [StryKaizer/NodeMCU-Somfy#1]
I have successfully installed the software on a ESP8266 and paired my blinds. Unfortunately, my blinds are not going fully up or down when sending the corresponding commands. I also tried with larger values for the repeat_count variable, but this did not help either. Any ideas how this could be fixed?

**Comment by StryKaizer** [comment]
So they are actually responding and moving up/down, but not entiraly? Or do they not respond at all?

**Comment by mschaeuble** [comment]
Yes exactly, the blinds move just a bit up or down and then do stop immediately again. I also tried with a repeat count of exactly 16 (but also higher and lower values) as described on https://nodemcu.readthedocs.io/en/master/en/modules/somfy/

**Comment by mschaeuble** [comment]
I did a test using an Arduino UNO and the exact same transmitter using the sketch from https://github.com/Nickduino/Somfy_Remote/blob/master/Somfy_Remote.ino and everything is working fine there.

**Comment by StryKaizer** [comment]
I see.  I'm using a repeat count of 5 myself, with no issues. I havent tested more to be honest, I think 5 should suffice (at least for my setup)

If you feel comfortable debugging, I'd love to know the real issue.
I'd suggest adding debug code (e.g. serial output) after the 4 somfy.sendcommand lines in somfyserver.lua and check how much they are being triggered (and which one, e.g. STOP should not trigger when firing UP)

Something else which might be happening is a timeout in the nodemcu server-part (might be related to the higher repeat count), or the nodemcu writing its config too soon to flash (which causes the nodemcu to be unresponsive for a few seconds).  You can raise the delay for writing to flash memory in config.lua, line 48 (default is after 65 seconds).

PS: the reason there is a delay for writing config to FLASH, is because the nodemcu will become unresponsive for a few seconds while doing so. Thats why we keep config in RAM memory for a while, to allow users to send multiple commands without being unavailable.

**Comment by mschaeuble** [comment]
After debugging a while the solution is simple: a repeat_count of 2 solves all my problems. So a repeat_count of 5 is probably NOT a good default ;-) (at least not in all cases).

Thanks for your help!

**Comment by StryKaizer** [comment]
Perfect, thanks for posting your solution!
